import jsPDF from "jspdf";
import { useState } from "react";
import "./App.css";
import DashboardStats from "./components/DashboardStats";
import Footer from "./components/Footer";
import Login from "./components/Login";
import Navbar from "./components/Navbar";
import ResultCard from "./components/ResultCard";
import UploadSection from "./components/UploadSection";

function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  const [prediction, setPrediction] = useState({
    result: "No Prediction Yet",
    confidence: "--",
    status: "Waiting",
  });

  const [loading, setLoading] = useState(false);

  const downloadReport = () => {
    const doc = new jsPDF();

    const currentDate = new Date().toLocaleString();

    doc.setFontSize(20);
    doc.text("AcousticSpace", 20, 20);

    doc.setFontSize(14);
    doc.text("Deepfake Audio Detection Report", 20, 30);

    doc.line(20, 35, 190, 35);

    doc.setFontSize(12);
    doc.text("Audio Information", 20, 48);

    doc.setFontSize(11);
    doc.text("Filename: Recording.wav", 25, 58);
    doc.text(`Date & Time: ${currentDate}`, 25, 68);

    doc.setFontSize(12);
    doc.text("Detection Result", 20, 85);

    doc.setFontSize(11);
    doc.text(`Prediction: ${prediction.result}`, 25, 95);
    doc.text(`Confidence: ${prediction.confidence}`, 25, 105);
    doc.text(`Status: ${prediction.status}`, 25, 115);

    doc.setFontSize(12);
    doc.text("Model Information", 20, 135);

    doc.setFontSize(11);
    doc.text("Model: AcousticCNN", 25, 145);
    doc.text("Framework: PyTorch", 25, 155);
    doc.text("Dataset: ASVspoof2019 LA", 25, 165);
    doc.text("Input: Mel Spectrogram", 25, 175);

    doc.setFontSize(12);
    doc.text("Detection Pipeline", 20, 195);

    doc.setFontSize(11);
    doc.text("Audio Upload", 25, 205);
    doc.text("↓", 25, 213);
    doc.text("Librosa Preprocessing", 25, 221);
    doc.text("↓", 25, 229);
    doc.text("Mel Spectrogram", 25, 237);
    doc.text("↓", 25, 245);
    doc.text("CNN Model", 25, 253);
    doc.text("↓", 25, 261);
    doc.text("Real / Fake Prediction", 25, 269);

    doc.line(20, 280, 190, 280);

    doc.setFontSize(9);
    doc.text(
      "Generated by AcousticSpace - Deepfake Audio Detection System",
      20,
      290
    );

    doc.save("AcousticSpace_Detection_Report.pdf");
  };

  const handleDetect = async (file) => {
    if (!file) return;

    setLoading(true);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch("http://127.0.0.1:8000/predict", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        throw new Error("Prediction request failed");
      }

      const data = await response.json();

      const predictionResult = data.prediction.prediction;
      const confidence = data.prediction.confidence;

      setPrediction({
        result:
          predictionResult === "Fake"
            ? "🚨 Fake Audio"
            : "✅ Real Audio",
        confidence: `${(confidence * 100).toFixed(2)}%`,
        status:
          predictionResult === "Fake"
            ? "AI Generated / Spoof"
            : "Authentic",
      });
    } catch (error) {
      console.error(error);

      setPrediction({
        result: "❌ Prediction Failed",
        confidence: "--",
        status: "Backend connection error",
      });
    } finally {
      setLoading(false);
    }
  };

  if (!isLoggedIn) {
    return <Login onLogin={() => setIsLoggedIn(true)} />;
  }

  return (
    <>
      <Navbar />
      <DashboardStats prediction={prediction} />

      <div className="hero">
        <h1>🎵 AcousticSpace</h1>

        <h2>Deepfake Audio Detection System</h2>

        <p>
          Upload an audio recording and detect whether it is
          <strong> Real </strong>
          or
          <strong> AI Generated</strong>.
        </p>

        <button>Learn More</button>
      </div>

      <UploadSection onDetect={handleDetect} />

      {loading ? (
        <h2 className="loading-text">Analyzing Audio...</h2>
      ) : (
        <>
          <ResultCard
            result={prediction.result}
            confidence={prediction.confidence}
            status={prediction.status}
          />

          {prediction.result !== "No Prediction Yet" && (
            <div className="report-section">
              <button onClick={downloadReport}>
                📄 Download PDF Report
              </button>
            </div>
          )}
        </>
      )}

      <Footer />
    </>
  );
}

export default App;